name: bloc_cube_shop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  flutter_bloc: ^7.3.0
  google_fonts: ^2.1.0
  json_annotation: ^4.0.0
  path_provider: ^2.0.3

#  shop_api:
#    path: packages/shop_api

  shop_repository:
    path: packages/shop_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  bloc_test: ^8.3.0
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true

